engines:
  eslint:
    enabled: true
    checks:
      linebreak-style:
        enabled: false
fixme:
    enabled: true
exclude_paths:
- "client/__tests__"
- "server/__test__"
- "coverage"
- "node_modules"