// export ActionConstants
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const GOOGLE_SIGN_IN_SUCCESS = 'GOOGLE_SIGN_IN_SUCCESS';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const CREATE_GROUP = 'CREATE_GROUP';
export const ADD_MEMBER = 'ADD_MEMBER';
export const GET_USER_GROUPS = 'GET_USER_GROUPS';
export const GET_MEMBERS_OF_GROUP = 'GET_MEMBERS_OF_GROUP';
export const ALL_USERS = 'ALL_USERS';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SEND_GROUP_MESSAGE = 'SEND_GROUP_MESSAGE';
export const SEND_GROUP_MESSAGE_ERROR = 'SEND_GROUP_MESSAGE_ERROR';
export const GET_GROUP_MESSAGE = 'GET_GROUP_MESSAGE';
