// export ActionConstants
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_ERROR = 'SIGN_UP_ERROR';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const GOOGLE_SIGN_IN_SUCCESS = 'GOOGLE_SIGN_IN_SUCCESS';
export const GOOGLE_SIGN_IN_ERROR = 'GOOGLE_SIGN_IN_ERROR';


export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';

export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';

export const ADD_MEMBER = 'ADD_MEMBER';
export const ADD_MEMBER_ERROR = 'ADD_MEMBER_ERROR';

export const GET_USER_GROUPS = 'GET_USER_GROUPS';
export const GET_MEMBERS_OF_GROUP = 'GET_MEMBERS_OF_GROUP';
export const ALL_USERS = 'ALL_USERS';


export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

export const SEND_GENERAL_MESSAGE = 'SEND_GENERAL_MESSAGE';
export const SEND_GROUP_MESSAGE = 'SEND_GROUP_MESSAGE';
export const GET_GROUP_MESSAGE = 'GET-GROUP_MESSAGE';
export const GET_GENERAL_MESSAGE = 'GET_GENERAL_MESSAGE';


export const READ_MESSAGE = 'READ_MESSAGE';
