// export ActionConstants
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_ERROR = 'SIGN_UP_ERROR';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';

export const GET_GROUPS = 'GET_GROUPS';
export const CREATE_NEW_GROUP = 'CREATE_NEW_GROUP';
export const ADD_NEW_GROUP = 'ADD_NEW_GROUP';

export const GENERAL = 'GENERAL';
export const ADD_MEMBER = 'ADD_MEMBER';
export const GET_MEMBERS = 'GET_MEMBERS';
export const GET_MEMBERS_OF_A_GROUP = 'GET_MEMBERS_OF_A_GROUP';

export const SEND_GENERAL_MESSAGE = 'SEND_GENERAL_MESSAGE';
export const SEND_GROUP_MESSAGE = 'SEND_GROUP_MESSAGE';
export const GET_GROUP_MESSAGE = 'GET-GROUP_MESSAGE';
export const GET_GENERAL_MESSAGE = 'GET_GENERAL_MESSAGE';


export const READ_MESSAGE = 'READ_MESSAGE';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';
