const ActionTypes = {
  SIGNUP_USER: 'SIGNUP_USER',
  SIGNIN_USER: 'SIGNIN_USER',
  SIGNOUT_USER: 'SIGNOUT_USER',
  DELETE_USER: 'DELETE_USER',
  UPDATE_USER: 'UPDATE_USER',
  CREATE_GROUP: 'CREATE_GROUP',
  ADDMEMBER_TO_GROUP: 'ADDMEMBER_TO_GROUP',
  SEND_BROADCAST_MESSAGE: 'SEND_BROADCAST_MESSAGE',
};
// Export ActionTypes
export default ActionTypes;
