const ActionTypes = {
  RESET: 'RESET',
  SIGNUP_USER: 'SIGNUP_USER',
  SIGNUP_USER_FAILED: 'SIGNUP_USER_FAILED',
  SIGNIN_USER: 'SIGNIN_USER',
  SIGNOUT_USER: 'SIGNOUT_USER',
  DELETE_USER: 'DELETE_USER',
  UPDATE_USER: 'UPDATE_USER',
  CREATE_GROUP: 'CREATE_GROUP',
  ADDMEMBER_TO_GROUP: 'ADDMEMBER_TO_GROUP',
  ADD_MEMBER: 'ADD_MEMBER',
  RECEIVE_MEMBER: 'RECEIVE_MEMBER',
  SEND_BROADCAST_MESSAGE: 'SEND_BROADCAST_MESSAGE',
};
// Export ActionTypes
export default ActionTypes;
